// SPDX-License-Identifier: MIT
pragma solidity 0.8.33;

import {IRebalancer} from "./interfaces/IRebalancer.sol";
import {AllocationProposal} from "./interfaces/IRebalancer.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @title AgentConsumer
/// @notice Entry point for the off-chain agent to submit allocation proposals
/// @dev Agent is a cron job wallet that calls proposeAllocation directly
///      No Chainlink Functions dependency — simpler, cheaper, operator controlled
contract AgentConsumer is Ownable {
    /// @notice Address of the Rebalancer contract
    address public immutable REBALANCER;

    /// @notice Address of the off-chain agent wallet (cron job)
    address public immutable AGENT;

    error NotAgent();
    error InvalidConstructorArguments();

    event AllocationProposed(address indexed caller, uint256 timestamp);

    modifier onlyAgent() {
        if (msg.sender != AGENT && msg.sender != owner()) revert NotAgent();
        _;
    }

    constructor(
        address _rebalancer,
        address _agent,
        address _owner
    ) Ownable(_owner) {
        if (
            _rebalancer == address(0) ||
            _agent == address(0) ||
            _owner == address(0)
        ) revert InvalidConstructorArguments();
        REBALANCER = _rebalancer;
        AGENT = _agent;
    }

    /// @notice Submits allocation proposal to rebalancer
    /// @dev Only callable by agent wallet or owner
    /// @param proposal The allocation proposal generated by off-chain agent
    function proposeAllocation(
        AllocationProposal calldata proposal
    ) external onlyAgent {
        IRebalancer(REBALANCER).proposeAllocation(proposal);
        emit AllocationProposed(msg.sender, block.timestamp);
    }
}
