// SPDX-License-Identifier: MIT
pragma solidity 0.8.33;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {AllocationProposal, IRebalancer} from "./interfaces/IRebalancer.sol";

/// @title AgentConsumer
/// @notice Thin entry point for the off-chain agent to submit allocation proposals to the Rebalancer
/// @dev The off-chain agent is a cron job wallet that periodically fetches APYs from Aave,
///      Compound, and Morpho, computes the optimal allocation, and calls proposeAllocation.
///      This contract enforces access control before forwarding to the Rebalancer.
///      No Chainlink Functions dependency — simpler, cheaper, and operator controlled.
///      Architecture: off-chain script → AgentConsumer → Rebalancer → HubVault → SpokeVaults
contract AgentConsumer is Ownable {
    // =========================================================================
    // State Variables
    // =========================================================================

    /// @notice Address of the Rebalancer contract that validates and executes proposals
    /// @dev Immutable — set once at deployment. AgentConsumer forwards all proposals here.
    address public immutable REBALANCER;

    /// @notice Address of the off-chain agent wallet (cron job EOA)
    /// @dev Immutable — the EOA that signs and submits allocation proposals on a schedule.
    ///      Authorized alongside owner to call proposeAllocation.
    address public immutable AGENT;

    // =========================================================================
    // Errors
    // =========================================================================

    /// @notice Thrown when caller is neither AGENT nor owner
    error NotAgent();

    /// @notice Thrown when constructor receives a zero address for any argument
    /// @dev Note: _owner == address(0) reverts with OwnableInvalidOwner from the Ownable
    ///      parent constructor before this check is reached
    error InvalidConstructorArguments();

    // =========================================================================
    // Events
    // =========================================================================

    /// @notice Emitted when a proposal is successfully forwarded to the Rebalancer
    /// @dev Does not indicate the proposal was accepted — Rebalancer may still revert
    ///      if guards fail. Emitted after the Rebalancer call succeeds.
    /// @param caller Address that submitted the proposal — either AGENT or owner
    /// @param timestamp Block timestamp when the proposal was submitted
    event AllocationProposed(address indexed caller, uint256 timestamp);

    // =========================================================================
    // Modifiers
    // =========================================================================

    /// @notice Restricts access to the AGENT wallet or the contract owner
    modifier onlyAgent() {
        if (msg.sender != AGENT && msg.sender != owner()) revert NotAgent();
        _;
    }

    // =========================================================================
    // Constructor
    // =========================================================================

    /// @notice Deploys AgentConsumer with immutable Rebalancer and agent references
    /// @dev Ownable(_owner) runs before the body — zero _owner reverts with
    ///      OwnableInvalidOwner before InvalidConstructorArguments is checked.
    ///      Zero _rebalancer or _agent reverts with InvalidConstructorArguments.
    /// @param _rebalancer Address of the Rebalancer contract
    /// @param _agent Address of the off-chain agent EOA (cron job wallet)
    /// @param _owner Address of the contract owner — should be a multisig before mainnet
    constructor(
        address _rebalancer,
        address _agent,
        address _owner
    ) Ownable(_owner) {
        if (
            _rebalancer == address(0) ||
            _agent == address(0) ||
            _owner == address(0)
        ) revert InvalidConstructorArguments();
        REBALANCER = _rebalancer;
        AGENT = _agent;
    }

    // =========================================================================
    // External Functions
    // =========================================================================

    /// @notice Forwards an allocation proposal from the off-chain agent to the Rebalancer
    /// @dev Only callable by AGENT or owner. All proposal validation occurs in the Rebalancer —
    ///      this contract is a pure access control wrapper. If Rebalancer reverts (cooldown,
    ///      invalid allocation, below threshold etc) this call reverts too.
    ///      Emits AllocationProposed only on success.
    /// @param proposal The AllocationProposal struct generated by the off-chain agent containing
    ///                 current and proposed allocations, APYs, chain selectors, and protocol ids
    function proposeAllocation(
        AllocationProposal calldata proposal
    ) external onlyAgent {
        IRebalancer(REBALANCER).proposeAllocation(proposal);
        emit AllocationProposed(msg.sender, block.timestamp);
    }
}
